//Project Euler: Problem 2: Even Fibonacci Numbers

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence that do not exceed the nth term, find the sum of the even-valued terms.
//Fibonacci formula
//F(0)=0
//F(1)=1
//F(n) = F(n-1) + F(n-2), n>1

function fiboEvenSum(n) {
 let fib = [1,2];
 let count = 0;
 for(let i=2; i<n; i++){
   fib.push(fib[i - 2] + fib[i - 1]);
   }
  for(let f of fib){
    if(f % 2 === 0) count += f;
  } 
 return count;
}

fiboEvenSum(10); //44
